--ELIMINACIÓN DE TABLAS
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE BANCO CASCADE CONSTRAINTS;
DROP TABLE DOSIS CASCADE CONSTRAINTS;
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE VIA_ADMINISTRACION CASCADE CONSTRAINTS;
DROP TABLE TIPO_MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE RECETA CASCADE CONSTRAINTS;
DROP TABLE TIPO_RECETA CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE DIGITADOR CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS;
DROP TABLE DIRECCION CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;

-- CREACIÓN TABLAS NORMALIZADAS - CASO 1
CREATE TABLE REGION(
id_region NUMBER (5),
nombre VARCHAR2 (30) NOT NULL,
CONSTRAINT PK_region PRIMARY KEY (id_region)
);

CREATE TABLE CIUDAD(
id_ciudad NUMBER (5),
nombre VARCHAR2 (30) NOT NULL,
cod_region NUMBER (5) NOT NULL,
CONSTRAINT PK_ciudad PRIMARY KEY (id_ciudad),
CONSTRAINT FK_ciud_reg FOREIGN KEY (cod_region) REFERENCES REGION (id_region)
);

CREATE TABLE COMUNA(
id_comuna NUMBER (5) GENERATED ALWAYS AS IDENTITY 
START WITH 1101
INCREMENT BY 1,
nombre VARCHAR2 (30) NOT NULL,
cod_ciudad NUMBER (5) NOT NULL,
CONSTRAINT PK_comuna PRIMARY KEY (id_comuna),
CONSTRAINT FK_comuna_ciud FOREIGN KEY (cod_ciudad) REFERENCES CIUDAD (id_ciudad)
);

CREATE TABLE PACIENTE(
rut_pac VARCHAR2 (25),
dv_pac CHAR (1) CHECK (dv_pac BETWEEN '0' AND '9' OR dv_pac IN ('k','K')),
pnombre VARCHAR2 (25) NOT NULL,
snombre VARCHAR2 (25) DEFAULT 'NO REGISTRA',
edad NUMBER (3) NOT NULL CHECK (edad > 0),
telefono NUMBER (11) NOT NULL,
CONSTRAINT PK_paciente PRIMARY KEY (rut_pac)
);

ALTER TABLE PACIENTE
MODIFY dv_pac NOT NULL;

CREATE TABLE DIRECCION(
id_direccion NUMBER (5),
calle VARCHAR2 (30) NOT NULL,
numero NUMBER (4) NOT NULL,
cod_comuna NUMBER (5) NOT NULL,
cod_pac VARCHAR (25) NOT NULL,
CONSTRAINT PK_direccion PRIMARY KEY (id_direccion),
CONSTRAINT FK_direc_comuna FOREIGN KEY (cod_comuna) REFERENCES COMUNA (id_comuna),
CONSTRAINT FK_direc_pac FOREIGN KEY (cod_pac) REFERENCES PACIENTE (rut_pac)
);

CREATE TABLE ESPECIALIDAD(
id_espe NUMBER (3) GENERATED ALWAYS AS IDENTITY
START WITH 100
INCREMENT BY 10,
nombre VARCHAR2 (30) NOT NULL
);

ALTER TABLE ESPECIALIDAD
ADD CONSTRAINT id_espe PRIMARY KEY (id_espe);

ALTER TABLE ESPECIALIDAD
RENAME CONSTRAINT id_espe TO PK_espe;

CREATE TABLE MEDICO(
rut_med NUMBER (8) CHECK (rut_med >0),
dv_med CHAR (1) NOT NULL CHECK (dv_med BETWEEN '0' AND '9' OR dv_med IN ('K', 'k')),
pnombre VARCHAR2 (25) NOT NULL,
snombre VARCHAR2 (25) DEFAULT 'NO REGISTRA',
papellido VARCHAR2 (25) NOT NULL,
sapellido VARCHAR2 (25) DEFAULT 'NO REGISTRA',
cod_espe NUMBER (3) NOT NULL,
CONSTRAINT PK_medico PRIMARY KEY (rut_med),
CONSTRAINT FK_med_espe FOREIGN KEY (cod_espe) REFERENCES ESPECIALIDAD (id_espe)
);

ALTER TABLE MEDICO
ADD telefono NUMBER (11) NOT NULL UNIQUE;

CREATE TABLE DIGITADOR(
id_digi NUMBER (4),
rut_digi NUMBER (8) NOT NULL CHECK (rut_digi > 0),
dv_digi CHAR (1) NOT NULL CHECK (dv_digi BETWEEN '0' AND '9' OR dv_digi IN ('k','K')),
pnombre VARCHAR2 (25) NOT NULL,
papellido VARCHAR2 (25) NOT NULL,
CONSTRAINT PK_digitador PRIMARY KEY (id_digi)
);

CREATE TABLE DIAGNOSTICO(
cod_diag NUMBER (3),
nombre VARCHAR2 (25) NOT NULL,
CONSTRAINT PK_diag PRIMARY KEY (cod_diag)
);

CREATE TABLE TIPO_RECETA(
id_tipo_rx NUMBER (3) GENERATED ALWAYS AS IDENTITY
START WITH 105
INCREMENT BY 10,
nombre VARCHAR2 (15) NOT NULL,
CONSTRAINT PK_tipo_rx PRIMARY KEY (id_tipo_rx)
);

CREATE TABLE RECETA(
cod_receta NUMBER (7),
observaciones VARCHAR2 (500),
fecha_emision DATE DEFAULT SYSDATE NOT NULL ,
fecha_vencimiento DATE,
id_digi NUMBER (4) NOT NULL,
rut_pac VARCHAR2 (25) NOT NULL,
id_diag NUMBER (3) NOT NULL,
rut_med NUMBER (8) NOT NULL,
id_tipo_rx NUMBER (3) NOT NULL,
CONSTRAINT PK_receta PRIMARY KEY (cod_receta),
CONSTRAINT FK_rx_diag FOREIGN KEY (id_diag) REFERENCES DIAGNOSTICO (cod_diag),
CONSTRAINT FK_rx_med FOREIGN KEY (rut_med) REFERENCES MEDICO (rut_med),
CONSTRAINT FK_rx_pac FOREIGN KEY (rut_pac) REFERENCES PACIENTE (rut_pac),
CONSTRAINT FK_tipo_rx FOREIGN KEY (id_tipo_rx) REFERENCES TIPO_RECETA (id_tipo_rx),
CONSTRAINT FK_rx_digi FOREIGN KEY (id_digi) REFERENCES DIGITADOR (id_digi)
);

CREATE TABLE TIPO_MEDICAMENTO(
id_tipo_medica NUMBER (3),
nombre VARCHAR2 (25) NOT NULL,
CONSTRAINT PK_tipo_medica PRIMARY KEY (id_tipo_medica)
);

CREATE TABLE VIA_ADMINISTRACION(
id_via_adminis NUMBER (3),
nombre VARCHAR2 (15) NOT NULL,
CONSTRAINT PK_via_adminis PRIMARY KEY (id_via_adminis)
);

CREATE TABLE MEDICAMENTO(
cod_medicamento NUMBER (7),
nombre VARCHAR2 (25) NOT NULL,
stock NUMBER (5) NOT NULL,
tipo_medica NUMBER (3) NOT NULL,
via_adminis NUMBER (3) NOT NULL,
CONSTRAINT PK_medicamento PRIMARY KEY (cod_medicamento),
CONSTRAINT FK_tipo_medica FOREIGN KEY (tipo_medica) REFERENCES TIPO_MEDICAMENTO (id_tipo_medica),
CONSTRAINT FK_via_medica FOREIGN KEY (via_adminis) REFERENCES VIA_ADMINISTRACION (id_via_adminis)
);

CREATE TABLE DOSIS(
id_medicamento NUMBER (7) NOT NULL,
id_receta NUMBER (7) NOT NULL,
descripcion_dosis VARCHAR2 (25) NOT NULL,
CONSTRAINT PK_dosis PRIMARY KEY (id_medicamento, id_receta),
CONSTRAINT FK_dosis_medica FOREIGN KEY (id_medicamento) REFERENCES MEDICAMENTO (cod_medicamento),
CONSTRAINT FK_dosis_rx FOREIGN KEY (id_receta) REFERENCES RECETA (cod_receta)
);

CREATE TABLE BANCO(
id_banco NUMBER (2),
nombre VARCHAR2 (25) NOT NULL,
CONSTRAINT PK_banco PRIMARY KEY (id_banco)
);

CREATE TABLE METODO_PAGO(
id_met_pago NUMBER (4),
nombre VARCHAR2 (25) NOT NULL,
CONSTRAINT PK_metodo PRIMARY KEY (id_met_pago)
);

CREATE TABLE PAGO(
cod_boleta NUMBER (6),
id_receta NUMBER (7) NOT NULL,
fecha_pago DATE DEFAULT SYSDATE NOT NULL,
monto_total VARCHAR2 (25) NOT NULL,
met_pago NUMBER (4) NOT NULL,
id_banco NUMBER (2),
CONSTRAINT PK_boleta PRIMARY KEY (cod_boleta),
CONSTRAINT FK_receta FOREIGN KEY (id_receta) REFERENCES RECETA (cod_receta),
CONSTRAINT FK_met_pago FOREIGN KEY (met_pago) REFERENCES METODO_PAGO (id_met_pago),
CONSTRAINT FK_pago_banco FOREIGN KEY (id_banco) REFERENCES BANCO (id_banco)
);

-- CASO 2
ALTER TABLE MEDICAMENTO
ADD (precio_unitario NUMBER (10,2) NOT NULL,
CONSTRAINT CHK_precio CHECK (precio_unitario BETWEEN 1000 AND 2000000)
);
    
ALTER TABLE METODO_PAGO
ADD CONSTRAINT met_permitido CHECK (nombre IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA'));

ALTER TABLE PACIENTE
DROP COLUMN edad;

ALTER TABLE PACIENTE
ADD fecha_nac DATE NOT NULL;
